### ISSUE TITLE
How to install BlxVimrc for neovim?

### ISSUE THREAD

**Issue by hacpai** [bramblex/BlxVimrc#5]

**Comment by bramblex** [comment]
Just make a soft link or clone repo to `~/.config/nvim`

example: `cp git clone https://github.com/bramblex/BlxVimrc.git ~/.config/nvim` 

If you want to use both vim and nevoim with same configuration, just make a soft link like `ln -s ~/.vim ~/.config/nvim`

**Comment by hacpai** [comment]
@bramblex Ok, it worked.
